# Generated by Django 3.1 on 2022-03-15 15:06

from django.db import migrations, models
import django.db.models.deletion
import sqlalchemy.sql.expression


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('customer', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='status',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, null=sqlalchemy.sql.expression.false, unique=sqlalchemy.sql.expression.true)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
                ('active', models.BooleanField(default=sqlalchemy.sql.expression.true)),
            ],
        ),
        migrations.CreateModel(
            name='typecontract',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, null=sqlalchemy.sql.expression.false, unique=sqlalchemy.sql.expression.true)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
                ('active', models.BooleanField(default=sqlalchemy.sql.expression.true)),
            ],
        ),
        migrations.CreateModel(
            name='contractform',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, null=sqlalchemy.sql.expression.true)),
                ('abstract', models.CharField(max_length=150, null=sqlalchemy.sql.expression.true)),
                ('signing_date', models.DateField(null=sqlalchemy.sql.expression.true)),
                ('value_date', models.DateField(blank=sqlalchemy.sql.expression.true, null=sqlalchemy.sql.expression.true)),
                ('expire_date', models.DateField(blank=sqlalchemy.sql.expression.true, null=sqlalchemy.sql.expression.true)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
                ('active', models.BooleanField(default=sqlalchemy.sql.expression.true)),
                ('contract_value', models.FloatField(null=sqlalchemy.sql.expression.true)),
                ('guaranteed_value', models.FloatField(blank=sqlalchemy.sql.expression.true, null=sqlalchemy.sql.expression.true)),
                ('upload_contract', models.FileField(null=sqlalchemy.sql.expression.true, upload_to='contract_form/%Y/%m')),
                ('note', models.TextField(blank=sqlalchemy.sql.expression.true, null=sqlalchemy.sql.expression.true)),
                ('customer', models.ForeignKey(null=sqlalchemy.sql.expression.true, on_delete=django.db.models.deletion.SET_NULL, to='customer.customer')),
                ('status', models.ForeignKey(null=sqlalchemy.sql.expression.true, on_delete=django.db.models.deletion.SET_NULL, to='contract.status')),
                ('typecontract', models.ForeignKey(null=sqlalchemy.sql.expression.false, on_delete=django.db.models.deletion.SET_NULL, to='contract.typecontract')),
            ],
        ),
        migrations.CreateModel(
            name='contract',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, null=sqlalchemy.sql.expression.false, unique=sqlalchemy.sql.expression.true)),
                ('abstract', models.CharField(max_length=150, null=sqlalchemy.sql.expression.false)),
                ('signing_date', models.DateField(null=sqlalchemy.sql.expression.false)),
                ('value_date', models.DateField(blank=sqlalchemy.sql.expression.true, null=sqlalchemy.sql.expression.true)),
                ('expire_date', models.DateField(blank=sqlalchemy.sql.expression.true, null=sqlalchemy.sql.expression.true)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
                ('active', models.BooleanField(default=sqlalchemy.sql.expression.true)),
                ('contract_value', models.FloatField(null=sqlalchemy.sql.expression.false)),
                ('guaranteed_value', models.FloatField(blank=None, null=sqlalchemy.sql.expression.true)),
                ('upload_file', models.FileField(null=sqlalchemy.sql.expression.true, upload_to='contracts/%Y/%m')),
                ('upload_contract', models.FileField(null=sqlalchemy.sql.expression.true, upload_to='contracts/%Y/%m')),
                ('note', models.TextField(blank=sqlalchemy.sql.expression.true, null=sqlalchemy.sql.expression.true)),
                ('customer', models.ForeignKey(null=sqlalchemy.sql.expression.true, on_delete=django.db.models.deletion.SET_NULL, to='customer.customer')),
                ('status', models.ForeignKey(null=sqlalchemy.sql.expression.true, on_delete=django.db.models.deletion.SET_NULL, to='contract.status')),
                ('typecontract', models.ForeignKey(null=sqlalchemy.sql.expression.false, on_delete=django.db.models.deletion.SET_NULL, to='contract.typecontract')),
            ],
        ),
        migrations.CreateModel(
            name='annex',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, null=sqlalchemy.sql.expression.false, unique=sqlalchemy.sql.expression.true)),
                ('abstract', models.CharField(max_length=150, null=sqlalchemy.sql.expression.true)),
                ('signing_date', models.DateField(null=sqlalchemy.sql.expression.false)),
                ('value_date', models.DateField(blank=sqlalchemy.sql.expression.true, null=sqlalchemy.sql.expression.true)),
                ('expire_date', models.DateField(blank=sqlalchemy.sql.expression.true, null=sqlalchemy.sql.expression.true)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
                ('active', models.BooleanField(default=sqlalchemy.sql.expression.true)),
                ('upload_contract', models.FileField(null=sqlalchemy.sql.expression.true, upload_to='contract_annex/%Y/%m')),
                ('contract', models.ForeignKey(null=sqlalchemy.sql.expression.false, on_delete=django.db.models.deletion.SET_NULL, to='contract.contract')),
            ],
        ),
    ]
