# Generated by Django 3.1 on 2022-03-16 01:00

from django.db import migrations, models
import django.db.models.deletion
import sqlalchemy.sql.expression


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0001_initial'),
        ('contract', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contractform',
            name='abstract',
            field=models.CharField(max_length=150, null=sqlalchemy.sql.expression.false),
        ),
        migrations.AlterField(
            model_name='contractform',
            name='customer',
            field=models.ForeignKey(null=sqlalchemy.sql.expression.false, on_delete=django.db.models.deletion.SET_NULL, to='customer.customer'),
        ),
        migrations.AlterField(
            model_name='contractform',
            name='expire_date',
            field=models.DateField(null=sqlalchemy.sql.expression.false),
        ),
        migrations.AlterField(
            model_name='contractform',
            name='name',
            field=models.CharField(max_length=100, null=sqlalchemy.sql.expression.false),
        ),
        migrations.AlterField(
            model_name='contractform',
            name='note',
            field=models.TextField(blank=sqlalchemy.sql.expression.true, null=sqlalchemy.sql.expression.false),
        ),
        migrations.AlterField(
            model_name='contractform',
            name='signing_date',
            field=models.DateField(null=sqlalchemy.sql.expression.false),
        ),
        migrations.AlterField(
            model_name='contractform',
            name='upload_contract',
            field=models.FileField(null=sqlalchemy.sql.expression.false, upload_to='contract_form/%Y/%m'),
        ),
        migrations.AlterField(
            model_name='contractform',
            name='value_date',
            field=models.DateField(null=sqlalchemy.sql.expression.false),
        ),
    ]
