# Generated by Django 3.1 on 2022-03-16 01:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contract', '0003_auto_20220316_0801'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contractform',
            name='name',
            field=models.CharField(max_length=100),
        ),
    ]
