# Generated by Django 3.1 on 2022-03-16 04:48

from django.db import migrations, models
import django.db.models.deletion
import sqlalchemy.sql.expression


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0002_auto_20220316_1148'),
        ('contract', '0004_auto_20220316_0803'),
    ]

    operations = [
        migrations.AddField(
            model_name='annex',
            name='user_created',
            field=models.CharField(blank=sqlalchemy.sql.expression.true, default=None, max_length=100),
        ),
        migrations.AddField(
            model_name='contract',
            name='user_created',
            field=models.CharField(blank=sqlalchemy.sql.expression.true, default=None, max_length=100),
        ),
        migrations.AlterField(
            model_name='annex',
            name='abstract',
            field=models.CharField(blank=sqlalchemy.sql.expression.true, default=None, max_length=150),
        ),
        migrations.AlterField(
            model_name='annex',
            name='contract',
            field=models.ForeignKey(null=sqlalchemy.sql.expression.true, on_delete=django.db.models.deletion.SET_NULL, to='contract.contract'),
        ),
        migrations.AlterField(
            model_name='annex',
            name='expire_date',
            field=models.DateField(blank=sqlalchemy.sql.expression.true, default=None),
        ),
        migrations.AlterField(
            model_name='annex',
            name='signing_date',
            field=models.DateField(blank=sqlalchemy.sql.expression.true, default=None),
        ),
        migrations.AlterField(
            model_name='annex',
            name='upload_contract',
            field=models.FileField(blank=sqlalchemy.sql.expression.true, default=None, upload_to='contract_annex/%Y/%m'),
        ),
        migrations.AlterField(
            model_name='annex',
            name='value_date',
            field=models.DateField(blank=sqlalchemy.sql.expression.true, default=None),
        ),
        migrations.AlterField(
            model_name='contract',
            name='abstract',
            field=models.CharField(default=None, max_length=150, null=sqlalchemy.sql.expression.false),
        ),
        migrations.AlterField(
            model_name='contract',
            name='contract_value',
            field=models.FloatField(default=None, null=sqlalchemy.sql.expression.false),
        ),
        migrations.AlterField(
            model_name='contract',
            name='expire_date',
            field=models.DateField(blank=sqlalchemy.sql.expression.true, default=None),
        ),
        migrations.AlterField(
            model_name='contract',
            name='guaranteed_value',
            field=models.FloatField(blank=sqlalchemy.sql.expression.true, default=None, null=sqlalchemy.sql.expression.true),
        ),
        migrations.AlterField(
            model_name='contract',
            name='note',
            field=models.TextField(blank=sqlalchemy.sql.expression.true, default=None, null=sqlalchemy.sql.expression.true),
        ),
        migrations.AlterField(
            model_name='contract',
            name='signing_date',
            field=models.DateField(default=None, null=sqlalchemy.sql.expression.false),
        ),
        migrations.AlterField(
            model_name='contract',
            name='status',
            field=models.ForeignKey(blank=sqlalchemy.sql.expression.true, null=sqlalchemy.sql.expression.true, on_delete=django.db.models.deletion.SET_NULL, to='contract.status'),
        ),
        migrations.AlterField(
            model_name='contract',
            name='typecontract',
            field=models.ForeignKey(null=sqlalchemy.sql.expression.true, on_delete=django.db.models.deletion.SET_NULL, to='contract.typecontract'),
        ),
        migrations.AlterField(
            model_name='contract',
            name='upload_contract',
            field=models.FileField(blank=sqlalchemy.sql.expression.true, default=None, upload_to='contracts/%Y/%m'),
        ),
        migrations.AlterField(
            model_name='contract',
            name='upload_file',
            field=models.FileField(blank=sqlalchemy.sql.expression.true, default=None, upload_to='contracts/%Y/%m'),
        ),
        migrations.AlterField(
            model_name='contract',
            name='value_date',
            field=models.DateField(blank=sqlalchemy.sql.expression.true, default=None),
        ),
        migrations.AlterField(
            model_name='contractform',
            name='abstract',
            field=models.CharField(blank=sqlalchemy.sql.expression.true, default=None, max_length=150),
        ),
        migrations.AlterField(
            model_name='contractform',
            name='contract_value',
            field=models.FloatField(blank=sqlalchemy.sql.expression.true, default=None),
        ),
        migrations.AlterField(
            model_name='contractform',
            name='customer',
            field=models.ForeignKey(blank=sqlalchemy.sql.expression.true, null=sqlalchemy.sql.expression.true, on_delete=django.db.models.deletion.SET_NULL, to='customer.customer'),
        ),
        migrations.AlterField(
            model_name='contractform',
            name='expire_date',
            field=models.DateField(blank=sqlalchemy.sql.expression.true, default=None),
        ),
        migrations.AlterField(
            model_name='contractform',
            name='guaranteed_value',
            field=models.FloatField(blank=sqlalchemy.sql.expression.true, default=None),
        ),
        migrations.AlterField(
            model_name='contractform',
            name='name',
            field=models.CharField(blank=sqlalchemy.sql.expression.true, max_length=100, null=sqlalchemy.sql.expression.false, unique=sqlalchemy.sql.expression.true),
        ),
        migrations.AlterField(
            model_name='contractform',
            name='note',
            field=models.TextField(blank=sqlalchemy.sql.expression.true, default=None),
        ),
        migrations.AlterField(
            model_name='contractform',
            name='signing_date',
            field=models.DateField(blank=sqlalchemy.sql.expression.true, default=None),
        ),
        migrations.AlterField(
            model_name='contractform',
            name='status',
            field=models.ForeignKey(blank=sqlalchemy.sql.expression.true, null=sqlalchemy.sql.expression.true, on_delete=django.db.models.deletion.SET_NULL, to='contract.status'),
        ),
        migrations.AlterField(
            model_name='contractform',
            name='typecontract',
            field=models.ForeignKey(blank=sqlalchemy.sql.expression.true, null=sqlalchemy.sql.expression.true, on_delete=django.db.models.deletion.SET_NULL, to='contract.typecontract'),
        ),
        migrations.AlterField(
            model_name='contractform',
            name='upload_contract',
            field=models.FileField(blank=sqlalchemy.sql.expression.true, default=None, upload_to='contract_form/%Y/%m'),
        ),
        migrations.AlterField(
            model_name='contractform',
            name='value_date',
            field=models.DateField(blank=sqlalchemy.sql.expression.true, default=None),
        ),
    ]
