# Generated by Django 3.1 on 2022-03-22 02:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import sqlalchemy.sql.expression


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('contract', '0005_auto_20220316_1148'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contract',
            name='user_created',
        ),
        migrations.AddField(
            model_name='annex',
            name='user',
            field=models.ForeignKey(blank=sqlalchemy.sql.expression.true, null=sqlalchemy.sql.expression.true, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=sqlalchemy.sql.expression.true,
        ),
        migrations.AddField(
            model_name='contract',
            name='user',
            field=models.ForeignKey(blank=sqlalchemy.sql.expression.true, null=sqlalchemy.sql.expression.true, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=sqlalchemy.sql.expression.true,
        ),
        migrations.AddField(
            model_name='contractform',
            name='user',
            field=models.ForeignKey(blank=sqlalchemy.sql.expression.true, null=sqlalchemy.sql.expression.true, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=sqlalchemy.sql.expression.true,
        ),
    ]
