# Generated by Django 3.1 on 2022-03-24 04:30

from django.db import migrations, models
import django.db.models.deletion
import sqlalchemy.sql.expression


class Migration(migrations.Migration):

    dependencies = [
        ('contract', '0007_auto_20220324_1128'),
    ]

    operations = [
        migrations.AlterField(
            model_name='annex',
            name='pricelist',
            field=models.ForeignKey(blank=sqlalchemy.sql.expression.true, default=None, null=sqlalchemy.sql.expression.true, on_delete=django.db.models.deletion.SET_NULL, to='contract.pricelist'),
        ),
        migrations.AlterField(
            model_name='contract',
            name='pricelist',
            field=models.ForeignKey(blank=sqlalchemy.sql.expression.true, default=None, null=sqlalchemy.sql.expression.true, on_delete=django.db.models.deletion.SET_NULL, to='contract.pricelist'),
        ),
        migrations.AlterField(
            model_name='contractform',
            name='pricelist',
            field=models.ForeignKey(blank=sqlalchemy.sql.expression.true, default=None, null=sqlalchemy.sql.expression.true, on_delete=django.db.models.deletion.SET_NULL, to='contract.pricelist'),
        ),
    ]
