# Generated by Django 3.1 on 2022-03-24 09:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contract', '0008_auto_20220324_1130'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='annex',
            options={'ordering': ['created_date']},
        ),
        migrations.AlterModelOptions(
            name='contract',
            options={'ordering': ['created_date']},
        ),
        migrations.AlterModelOptions(
            name='contractform',
            options={'ordering': ['created_date']},
        ),
        migrations.AlterModelOptions(
            name='pricelist',
            options={'ordering': ['created_date']},
        ),
        migrations.AlterModelOptions(
            name='status',
            options={'ordering': ['created_date']},
        ),
        migrations.AlterModelOptions(
            name='typecontract',
            options={'ordering': ['created_date']},
        ),
    ]
