# Generated by Django 3.1 on 2022-03-25 02:12

from django.db import migrations, models
import django.db.models.deletion
import sqlalchemy.sql.expression


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0006_auto_20220325_0912'),
        ('contract', '0010_auto_20220324_1704'),
    ]

    operations = [
        migrations.AddField(
            model_name='annex',
            name='customer',
            field=models.ForeignKey(blank=sqlalchemy.sql.expression.true, null=sqlalchemy.sql.expression.true, on_delete=django.db.models.deletion.SET_NULL, to='customer.customer'),
            preserve_default=sqlalchemy.sql.expression.true,
        ),
        migrations.AddField(
            model_name='annex',
            name='director',
            field=models.ForeignKey(blank=sqlalchemy.sql.expression.true, null=sqlalchemy.sql.expression.true, on_delete=django.db.models.deletion.SET_NULL, to='customer.director'),
            preserve_default=sqlalchemy.sql.expression.true,
        ),
        migrations.AddField(
            model_name='contract',
            name='director',
            field=models.ForeignKey(null=sqlalchemy.sql.expression.true, on_delete=django.db.models.deletion.SET_NULL, to='customer.director'),
            preserve_default=sqlalchemy.sql.expression.true,
        ),
        migrations.AddField(
            model_name='contractform',
            name='director',
            field=models.ForeignKey(blank=sqlalchemy.sql.expression.true, null=sqlalchemy.sql.expression.true, on_delete=django.db.models.deletion.SET_NULL, to='customer.director'),
            preserve_default=sqlalchemy.sql.expression.true,
        ),
    ]
