# Generated by Django 3.1 on 2022-03-26 04:10

from django.db import migrations, models
import django.db.models.deletion
import sqlalchemy.sql.expression


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0006_auto_20220325_0912'),
        ('contract', '0012_auto_20220326_1101'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contract',
            name='contract_value',
            field=models.FloatField(blank=sqlalchemy.sql.expression.true, default=None, null=sqlalchemy.sql.expression.true),
        ),
        migrations.AlterField(
            model_name='contract',
            name='customer',
            field=models.ForeignKey(blank=sqlalchemy.sql.expression.true, null=sqlalchemy.sql.expression.true, on_delete=django.db.models.deletion.SET_NULL, to='customer.customer'),
        ),
        migrations.AlterField(
            model_name='contract',
            name='director',
            field=models.ForeignKey(blank=sqlalchemy.sql.expression.true, null=sqlalchemy.sql.expression.true, on_delete=django.db.models.deletion.SET_NULL, to='customer.director'),
        ),
        migrations.AlterField(
            model_name='contract',
            name='signing_date',
            field=models.DateField(blank=sqlalchemy.sql.expression.true, default=None, null=sqlalchemy.sql.expression.true),
        ),
        migrations.AlterField(
            model_name='contract',
            name='typecontract',
            field=models.ForeignKey(blank=sqlalchemy.sql.expression.true, null=sqlalchemy.sql.expression.true, on_delete=django.db.models.deletion.SET_NULL, to='contract.typecontract'),
        ),
    ]
