# Generated by Django 3.1 on 2022-03-26 04:48

from django.db import migrations, models
import sqlalchemy.sql.expression


class Migration(migrations.Migration):

    dependencies = [
        ('contract', '0013_auto_20220326_1110'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contract',
            name='contract_value',
            field=models.CharField(blank=sqlalchemy.sql.expression.true, default=None, max_length=100, null=sqlalchemy.sql.expression.true),
        ),
        migrations.AlterField(
            model_name='contract',
            name='guaranteed_value',
            field=models.CharField(blank=sqlalchemy.sql.expression.true, default=None, max_length=100, null=sqlalchemy.sql.expression.true),
        ),
        migrations.AlterField(
            model_name='contractform',
            name='contract_value',
            field=models.CharField(blank=sqlalchemy.sql.expression.true, default=None, max_length=100),
        ),
        migrations.AlterField(
            model_name='contractform',
            name='guaranteed_value',
            field=models.CharField(blank=sqlalchemy.sql.expression.true, default=None, max_length=100),
        ),
    ]
