# Generated by Django 3.1 on 2022-03-28 12:00

from django.db import migrations, models
import django.db.models.deletion
import sqlalchemy.sql.expression


class Migration(migrations.Migration):

    dependencies = [
        ('contract', '0016_auto_20220328_1536'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='annex',
            name='typecontract',
        ),
        migrations.AddField(
            model_name='annex',
            name='contract',
            field=models.ForeignKey(blank=sqlalchemy.sql.expression.true, null=sqlalchemy.sql.expression.true, on_delete=django.db.models.deletion.CASCADE, to='contract.contract'),
            preserve_default=sqlalchemy.sql.expression.true,
        ),
        migrations.AlterField(
            model_name='annex',
            name='name',
            field=models.CharField(blank=sqlalchemy.sql.expression.true, max_length=100, null=sqlalchemy.sql.expression.false),
        ),
    ]
