# Generated by Django 4.0.2 on 2022-04-16 05:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contract', '0018_contract_delegation_alter_annex_id_alter_contract_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='group',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('NameGroup', models.CharField(max_length=255)),
                ('Member', models.JSONField()),
                ('Created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AddField(
            model_name='contract_delegation',
            name='group',
            field=models.IntegerField(default=0),
        ),
    ]
