# Generated by Django 4.0.2 on 2022-04-16 13:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contract', '0019_group_contract_delegation_group'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contract_delegation',
            options={'ordering': ['created']},
        ),
    ]
