# Generated by Django 4.0.2 on 2022-04-20 15:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contract', '0021_group_createbyuserid'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='group',
            new_name='group_s',
        ),
    ]
