# Generated by Django 4.0.2 on 2022-04-20 15:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contract', '0022_rename_group_group_s'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='group_s',
            new_name='groupModel',
        ),
    ]
