# Generated by Django 4.0.2 on 2022-04-21 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contract', '0023_rename_group_s_groupmodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='groupmodel',
            name='Contract',
            field=models.JSONField(default=[]),
        ),
    ]
