# Generated by Django 3.1 on 2022-03-15 15:06

from django.db import migrations, models
import django.db.models.deletion
import sqlalchemy.sql.expression


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='director',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, null=sqlalchemy.sql.expression.false)),
                ('position', models.CharField(max_length=150, null=sqlalchemy.sql.expression.true)),
                ('authorization', models.CharField(max_length=255, verbose_name=False)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
                ('active', models.BooleanField(default=sqlalchemy.sql.expression.true)),
            ],
        ),
        migrations.CreateModel(
            name='customer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, null=sqlalchemy.sql.expression.false, unique=sqlalchemy.sql.expression.true)),
                ('tax_code', models.CharField(max_length=25, null=sqlalchemy.sql.expression.true, unique=sqlalchemy.sql.expression.true)),
                ('phone', models.CharField(max_length=20, null=sqlalchemy.sql.expression.true)),
                ('address', models.CharField(max_length=255, null=sqlalchemy.sql.expression.true)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
                ('active', models.BooleanField(default=sqlalchemy.sql.expression.true)),
                ('director', models.ForeignKey(null=sqlalchemy.sql.expression.true, on_delete=django.db.models.deletion.SET_NULL, to='customer.director')),
            ],
        ),
    ]
