# Generated by Django 3.1 on 2022-03-16 04:48

from django.db import migrations, models
import sqlalchemy.sql.expression


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='tax_code',
            field=models.CharField(max_length=25, null=sqlalchemy.sql.expression.false, unique=sqlalchemy.sql.expression.true),
        ),
        migrations.AlterField(
            model_name='director',
            name='authorization',
            field=models.CharField(blank=sqlalchemy.sql.expression.true, max_length=255),
        ),
    ]
