# Generated by Django 3.1 on 2022-03-24 04:28

from django.db import migrations, models
import django.db.models.deletion
import sqlalchemy.sql.expression


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0003_auto_20220322_1057'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='director',
        ),
        migrations.AddField(
            model_name='director',
            name='customer',
            field=models.ForeignKey(null=sqlalchemy.sql.expression.true, on_delete=django.db.models.deletion.SET_NULL, to='customer.customer'),
            preserve_default=sqlalchemy.sql.expression.true,
        ),
    ]
