# Generated by Django 3.1 on 2022-03-24 09:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0004_auto_20220324_1128'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customer',
            options={'ordering': ['created_date']},
        ),
        migrations.AlterModelOptions(
            name='director',
            options={'ordering': ['created_date']},
        ),
    ]
